### ISSUE TITLE
can't find stock on investpy

### ISSUE THREAD

**Issue by decent1985** [alvarob96/investpy#104]
I tried to find all stocks for my country, which is around 1600, yet only to find 1000 of them.
For example : I DO find “3611” on investing.com, but can’t find it on  Investpy.
*********code*************

df=pd.DataFrame(investpy.stocks.get_stocks_list(country='taiwan'))
print(df)
search_results = investpy.search_stocks(by='isin', value='TW0003611000')
print(search_results.head())

*********result*************
        0
0    1101
1    1102
2    1103
3    1104
4    1108
..    ...
995  3217
996  3218
997  3219
998  3221
999  3224

[1000 rows x 1 columns]

RuntimeError                              Traceback (most recent call last)
<ipython-input-7-54ef6298532d> in <module>
----> 1 search_results = investpy.search_stocks(by='isin', value='TW0003611000')
      2 print(search_results.head())

C:\ProgramData\Anaconda3\lib\site-packages\investpy\stocks.py in search_stocks(by, value)
   1337 
   1338     if len(search_result) == 0:
-> 1339         raise RuntimeError('ERR#0043: no results were found for the introduced ' + str(by) + '.')
   1340 
   1341     search_result.drop(columns=['matches'], inplace=True)

RuntimeError: ERR#0043: no results were found for the introduced isin.

**Comment by alvarob96** [comment]
Hi @decent1985, thank you for reporting this issue!

I am currently working on it, but as a current solution check the following piece of code using **investpy** which uses Investing.com search engine to search financial products that may be not properly indexed, using the function `investpy.search()`:

![issue](https://user-images.githubusercontent.com/36760800/74717787-499b2180-5231-11ea-970e-82b8e77f2071.png)

**Warning**: _I found a problem when retrieving recent/historical data from `search_results` provided by the previous function which I will be fixing ASAP. Stay tuned for updates!_

**Comment by alvarob96** [comment]
I did some research and this issue is related to Investing.com functionality, which I can do nothing about it apart from proposing you to use `investpy.search()` function. So on, this issue will not be worked on currently until a proper solution is found.

**Comment by decent1985** [comment]
Thank you so much!! the alternative of using investpy.search helps a lot
Álvaro Bartolomé del Canto <notifications@github.com> 於 2020年2月27日 週四
下午11:32 寫道：
