### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by lefig** [alvarob96/investpy#106]
This is an outstanding project and thank you for your hard work.

I have been looking for a replacement for Yfinancials for some time as Yahoo has poor data quality. I happen to rely on Investing too.

And I particularly like the symbol search feature.

Excellent work.

**Comment by alvarob96** [comment]
Thanks a lot @lefig! Stay tuned since later this week I will be releasing **investpy**'s new version which includes new features and useful functionalities that you may like.
