### ISSUE TITLE
error of running sample code of getting asset historical data

### ISSUE THREAD

**Issue by poboquant** [alvarob96/investpy#111]
hello,
when I was running sample code 

"import investpy

df = investpy.get_etf_recent_data(etf='bbva accion dj eurostoxx 50',
                                  country='spain')
print(df.head())"

error happened:

"Traceback (most recent call last):
  File "d:/quant/python/investpy-test.py", line 4, in <module>
    country='spain')
  File "D:\program\anaconda\lib\site-packages\investpy\etfs.py", line 399, in get_etf_recent_data
    raise RuntimeError("ERR#0004: data retrieval error while scraping.")
RuntimeError: ERR#0004: data retrieval error while scraping."

for sample code of getting any asset historical data,same error happens.

but the sample code of search data ran ok.

please help.Thanks.

**Comment by alvarob96** [comment]
Hi @poboquant!

I tried your piece of code in an empty Jupyter Notebook, and it works perfectly for me as you can see below:

![issue-1](https://user-images.githubusercontent.com/36760800/75766467-81ca5600-5d41-11ea-8215-11c0ffc29075.png)

If you have problem, please update **investpy** to the latest version 0.9.14 and if it does not work still, just send me more information like where are you sending the request from (country), if you can see Investing.com properly, etc.

**Comment by poboquant** [comment]
alvarob96,

Thanks for the reply.My request is from China, and in the broswer,when accessing investing.com,the browser will automatically redirect it to  https://cn.investing.com . I guessed this may caused the issue.

**Comment by alvarob96** [comment]
Hi @poboquant!

Maybe try connecting using an VPN because maybe Investing.com is limited or restricted for China users, just let me know if you are able to use investpy using a VPN.

Hope this helped you!

**Comment by missing0313** [comment]
Hi @alvarobartt ! 
Sorry to bother you. 
I'm from China, too. After using VPN, I can access Investing.com directly on the website, but same error still happens, which is "ERR#0004: data retrieval error while scraping". 
Hope you can help me. Thanks!

**Comment by david2588e** [comment]
Hallo All:
For Chinese visitor, using VPN can help solve this issue and I checked it .
It works well,but maybe improve it via software, to get the data without VPN is better.
Maybe the data header is not compatible to the existing setting
Thanks

**Comment by Mrziiz** [comment]
Hello @alvarobartt 
I have same error today, but even few days ago evething worked fine...
I've checekd site and I have no any rediretcs from invexting.com

**Comment by AlejandroBaron** [comment]
Hello, I'm getting the same error with a code that worked like a charm yesterday, but only with some funds 

```
granularity = "Monthly"
start_date  = '01/01/2010'
end_date    = '01/01/2020'

funds = ['Vanguard U.s. Opportunities Fund Investor Eur Accumulation',
         'Vanguard European Stock Index Fund Investor Eur Accumulation',
         'Vanguard Emerging Markets Stock Index Fund Investor Eur Accumulation',
         'Vanguard Japan Stock Index Fund Institutional Eur Accumulation']


for f in funds:
    print(f)
    df = investpy.get_fund_historical_data(fund=f,
                                                                country="ireland",
                                                                from_date=start_date,
                                                                to_date=end_date,
                                                                interval = granularity)
   # Rest of my code
```

Could it be related to IP limitations?  I'm European so no regional blocking I'm assuming

**Comment by SlippingForest** [comment]
Hi. i have ERR#0004: data retrieval error while scraping. From Ukraine

**Comment by gbaettig** [comment]
Hi, I am facing the same issue... I get the "ERR###4: data retrieval error while scraping" error... I'm located in Switzerland.. It was working just fine two days ago

**Comment by alvarobartt** [comment]
@AlejandroBaron, @SlippingForest, @gbaettig you need to upgrade `investpy` to the latest version that was released yesterday as bug-fix, just use the following command:

```bash
pip install investpy==1.0.5
```

This has been due to some Investing.com inner changes on the accepted headers of the requests which was breaking investpy.

Sorry for the inconvenience! :weary:

**Comment by ZexuanAIE** [comment]
I tested both 1.0.5 and 1.0.6, but still got same error.
error:  ERR#0004: data retrieval error while scraping.

**Comment by alvarobartt** [comment]
Hi @ZexuanAIE, can you please open a new issue reporting this and including if possible either some screenshots or the function call that you are using? So that I can reproduce and start tackling the issue again, even though the `pytest` that I've just run seems to be working properly...

Also, I want you to open a new issue as some other users also reported this issue again, so it may be because of something that I cannot manage, maybe the region or something like that... Anyway, please give me as many details as possible in the new issue you create please! :pray:

**Comment by ZexuanAIE** [comment]
Sorry, my bad. I upgraded local version but forgot to update the requirements.txt, so the docker image was not upgraded. Now everything works. Thanks.
