### ISSUE TITLE
rename debug arg to test & instead use debug for printing function behaviour

### ISSUE THREAD

**Issue by alvarob96** [alvarob96/investpy#18]
- Rename `debug` argument on functions to `test`, as the purpose of that argument is to speed up tests made via pytest.
- Use `debug` argument for printing debug messages in the case that the user wants to check what is happening inside the function api call to Investing.

To implement the `debug` behaviour to show or hide print output as the param is respectively `True` or `False`, will be done as described on [stackoverflow](https://stackoverflow.com/a/8391735/9705070) by @brigand (credits to him):

![imagen](https://user-images.githubusercontent.com/36760800/63091658-5a579b80-bf5f-11e9-8391-a307c42ea6b5.png)

**Comment by brigand** [comment]
Hi @alvarob96.

If possible, use a logging interface in your own code that you can enable/disable as needed instead of replacing `sys.stdout`. The SO question was about a situation where the `print` calls were entirely outside of the user's control.

**Comment by alvarob96** [comment]
Thank you @brigand! 

I will use [logging](https://docs.python.org/3/library/logging.html) interface with debug messages for the package if argument `debug` is _True_.

Whenever it is finished I will reference this issue on the corresponding commit, as it will be done for **investpy 0.8.8** release.
