### ISSUE TITLE
develop functions to support currencies data retrieval

### ISSUE THREAD

**Issue by alvarob96** [alvarob96/investpy#29]
As equities/stocks, funds and etfs retrieval functions have already been developed, the addition of **currency retrieval functions is proposed**, since currencies are one of the main financial products data offered by [Investing.com](https://www.investing.com).

So, for example, as already developed for equities, the development of the same functions adapted to currency data retrieval is proposed in order to improve [investpy](https://github.com/alvarob96/investpy) usage and coverage of the financial markets data.

This is supposed to lead to the development of the following functions:
```python
import investpy

investpy.get_currency_crosses()
investpy.get_currency_crosses_list()
investpy.get_currency_crosses_dict()
investpy.get_available_currencies()
investpy.get_currency_cross_recent_data()
investpy.get_currency_cross_historical_data()
investpy.get_currency_crosses_overview()
```

**Comment by Djaramillo39** [comment]
Additional to currency retrieval, could it be posisble to have main stock indices (Ex. Dow 30) and raw material prices (Ex. Bren Oil)?

**Comment by alvarob96** [comment]
Hi @Djaramillo39, the answer to your question is yes, as the main intention of **investpy** is to be able to retrieve all the data indexed in [Investing.com](https://www.investing.com), so on, if you feel that **investpy** needs new features or some fixes, feel free to open an [issue](https://github.com/alvarob96/investpy/issues).

As both `Indices` and `Commodities` are indexed in Investing.com and its development is possible, you should open one issue for each feature you want **investpy** to develop. This issue management is made in order not to overlap tasks, so feel free to open the issues and I will develop and implement them as fast as I can!

Thank you for your support! 💪

**Comment by Djaramillo39** [comment]
Will do! Thank you so much for ñyour development and support! It is a great tool!

**Comment by davetromp** [comment]
@alvarob96 I can work on this one if you want. If you want, let me know on which branch you want met to implement it.

**Comment by alvarob96** [comment]
@davetromp thank you so much! I will check your pull request later today or tomorrow and consider on accepting the pull request. As I already saw everything is properly structured but I will need to add more tests and maybe check spelling/grammar.

Make sure to star the repo and be watching to notified about all conversations! ⭐️ :octocat:

**Comment by alvarob96** [comment]
As explained in #46, the PR sent by @davetromp needs to be revised and checked before launching the new release and, so on, before setting this issue as finished.

**Comment by alvarob96** [comment]
Major revision and almost completely redone `currency_crosses.py` file since the currency crosses retrieval was poor and lack of information: e7ab4b7d311f997607b9e17754e8d3a2c94b974d

**Comment by alvarob96** [comment]
The major revision of the PR #41 has been completed! **currency_crosses data is available for retrieval**! 

Both `docs/` and `tests/` are up-to-date and the release 0.9.6 is out!

Referencing commits: da541edf15353f156f5af268c2ceae974d34efbc and b11c5c158cda2124715e77c723613e55535d2f7b
