### ISSUE TITLE
development of main indices retrieval

### ISSUE THREAD

**Issue by Djaramillo39** [alvarob96/investpy#36]
In addition to the existing functionalities, could it be possible to include the main indices retrieval (Ex. Dow 30).

Thank you for your help!

**Comment by alvarob96** [comment]
**Indices functions have been created** in `indices.py` but they need to be both referenced from the `__init__.py` file and covered in the `tests/` to go back to previous codecov percentage. Tha commit referencing this issue previously is: d78a5ef3a7908b694d0d1f466c6a67b490ab549c
