### ISSUE TITLE
Invalid Volume on the result

### ISSUE THREAD

**Issue by sea98745** [alvarob96/investpy#73]
hi Alvarob96,

Notice that the is always given stock volume is 0 as what you display is you doc

import investpy

df = investpy.get_stock_historical_data(stock='bbva',
                                        country='spain',
                                        from_date='01/01/2010',
                                        to_date='01/01/2019')
print(df.head())

             Open   High    Low  Close  Volume Currency
Date
2010-01-04  12.73  12.96  12.73  12.96       0      EUR
2010-01-05  13.00  13.11  12.97  13.09       0      EUR
2010-01-06  13.03  13.17  13.02  13.12       0      EUR
2010-01-07  13.02  13.11  12.93  13.05       0      EUR
2010-01-08  13.12  13.22  13.04  13.18       0      EUR

After looking at the code, notice you are assigning the volume if you see the 'K','M' and 'B', else the volume will be assigned to 0 as below
 
            stock_volume = 0
            if info[5].__contains__('K'):
                stock_volume = int(float(info[5].replace('K', '').replace(',', '')) * 1e3)
            elif info[5].__contains__('M'):
                stock_volume = int(float(info[5].replace('M', '').replace(',', '')) * 1e6)
            elif info[5].__contains__('B'):
                stock_volume = int(float(info[5].replace('B', '').replace(',', '')) * 1e9)

Is this a bug ?

If I add the "else ..."to get the volume value, it will return the proper volume data
if info[5].__contains__('K'):
                        stock_volume = int(float(info[5].replace('K', '').replace(',', '')) * 1e3)
                    elif info[5].__contains__('M'):
                        stock_volume = int(float(info[5].replace('M', '').replace(',', '')) * 1e6)
                    elif info[5].__contains__('B'):
                        stock_volume = int(float(info[5].replace('B', '').replace(',', '')) * 1e9)
                    **_else:
                        stock_volume = int(info[5])_**

**Comment by alvarob96** [comment]
Thank you for reporting this issue @sea98745!

I will work on it since it seems to be a relevant feature to fix. Anyways it has been working the past days, I will need to check if it is an Investing.com problem or mine. This problem may have been produced when I moved from the spanish Investing site (es.) to the global one (www.).

I will let you know as soon as possible this issue is fixed! Thank you for your tip anyways.

**Comment by dirkargyle** [comment]
Can you help? how to correct the 0 value?

**Comment by sea98745** [comment]
Hi there

This is how I  fixed the issue

if info[5].__contains__('K'):
                stock_volume = int(float(info[5].replace('K',
'').replace(',', '')) * 1e3)
            elif info[5].__contains__('M'):
                stock_volume = int(float(info[5].replace('M',
'').replace(',', '')) * 1e6)
            elif info[5].__contains__('B'):
                stock_volume = int(float(info[5].replace('B',
'').replace(',', '')) * 1e9)
          *else:*
*            stock_volume = int(info[5]) *

**Comment by alvarob96** [comment]
Hi @dirkargyle and @sea98745!

I already solved it in investpy and it will be updated in the next release in a few days! Be sure to be watching the repository in order to get notified whenever the package new version is released.

Thank you!

**Comment by dirkargyle** [comment]
Thank you

**Comment by alvarob96** [comment]
Hi @dirkargyle and @sea98745!

The new investpy release 0.9.11 is out! In this release all the issues have been fixed, including the one you described here. So you can now update the package via pip using: `pip install investpy==0.9.11`.

Thank you! ⭐️ :octocat:
