### ISSUE TITLE
Stock information data

### ISSUE THREAD

**Issue by rdoktor** [alvarob96/investpy#77]
Dear, I am very interested by the Investpy library and I would like to know if it could be possible to improve the equivalent of investpy.get_funds_information but for stock as investpy.get_stock_information for instance in order to get stock fundamental data such as market cap...
Thanks in advance,
Best regards,
Reynald

**Comment by alvarob96** [comment]
Hi @rdoktor! 

The new investpy release 0.9.11 is out! In this release all the issues have been fixed, including the one you described here. So you can now update the package via pip using: `pip install investpy==0.9.11`.

Thank you! ⭐️ :octocat:

**Comment by rdoktor** [comment]
Thanks a lot Alvaro ! !
