### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by kuhytitusdlz** [alvarob96/investpy#85]
`c:\>pip install investpy
Collecting investpy
  Using cached https://files.pythonhosted.org/packages/cf/e8/1378dbf23b3390296fe5eff5155317eb782b59093a15714cfa77ceb4f42b/investpy-0.9.11.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxx\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-o9ukmj96\\investpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-o9ukmj96\\investpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxx\AppData\Local\Temp\pip-install-o9ukmj96\investpy\pip-egg-info'
         cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-o9ukmj96\investpy\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-o9ukmj96\investpy\setup.py", line 35, in <module>
        install_requires=parse_requirements(),
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-o9ukmj96\investpy\setup.py", line 17, in parse_requirements
        with io.open('requirements.txt', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by alvarob96** [comment]
Thank you for reporting this issue @kuhytitusdlz! I made a mistake on `parse_requirements` function on installation because I used a wrong version in the CI. Please stay tunned since I will be fixing this issue tomorrow and so on, a new investpy version will be released.

**Comment by GMZ21931** [comment]
I had the same error when used "$ python -m pip install investpy". (having Python 2.7)

When tried to install using "$ python -m pip install https://github.com/alvarob96/investpy/archive/master.zip", it shows:
RuntimeError: Python version >= 3.5 required.

Seems installation from GitHub via PyPI is a better choice. :)

**Comment by kuhytitusdlz** [comment]
Still not working(

`c:\temp>pip --no-cache-dir install investpy
Collecting investpy
  Downloading https://files.pythonhosted.org/packages/cf/e8/1378dbf23b3390296fe5eff5155317eb782b59093a15714cfa77ceb4f42b/investpy-0.9.11.tar.gz (4.3MB)
     |████████████████████████████████| 4.3MB 819kB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\xxx\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-o8hgmgsc\\investpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-install-o8hgmgsc\\investpy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxx\AppData\Local\Temp\pip-install-o8hgmgsc\investpy\pip-egg-info'
         cwd: C:\Users\xxx\AppData\Local\Temp\pip-install-o8hgmgsc\investpy\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-o8hgmgsc\investpy\setup.py", line 35, in <module>
        install_requires=parse_requirements(),
      File "C:\Users\xxx\AppData\Local\Temp\pip-install-o8hgmgsc\investpy\setup.py", line 17, in parse_requirements
        with io.open('requirements.txt', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by kuhytitusdlz** [comment]
Installed with command
pip install https://github.com/alvarob96/investpy/archive/master.zip

**Comment by alvarob96** [comment]
Hi @kuhytitusdlz and @GMZ21931,

as you can see, investpy is just available on Python 3.5 or higher, so installing it with Python 2.7 or any other version rather than 3.5 or higher will error. Anyways I mentioned that 0.9.11 release installation does not work due to a `setup.py` configuration error which has been fixed in 0.9.12 release.

In order to install new investpy working version you can use:

`python -m pip install investpy==0.9.12 --upgrade --user`

Thank you!

**Comment by kuhytitusdlz** [comment]
by default tried install 0.9.11
```c:\>pip install investpy
Collecting investpy
  Using cached https://files.pythonhosted.org/packages/cf/e8/1378dbf23b3390296fe5eff5155317eb782b59093a15714cfa77ceb4f42b/investpy-0.9.11.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-
install-2dllev50\\investpy\\setup.py'"'"'; __file__='"'"'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-2dllev50\\investpy\\setup.py'"'"';f=getat
tr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'
))' egg_info --egg-base 'C:\Users\admin\AppData\Local\Temp\pip-install-2dllev50\investpy\pip-egg-info'
         cwd: C:\Users\admin\AppData\Local\Temp\pip-install-2dllev50\investpy\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\admin\AppData\Local\Temp\pip-install-2dllev50\investpy\setup.py", line 35, in <module>
        install_requires=parse_requirements(),
      File "C:\Users\admin\AppData\Local\Temp\pip-install-2dllev50\investpy\setup.py", line 17, in parse_requirements
        with io.open('requirements.txt', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kuhytitusdlz** [comment]
0.9.12 not abailable
```
c:\>python -m pip install investpy==0.9.12 --upgrade --user
ERROR: Could not find a version that satisfies the requirement investpy==0.9.12 (from versions: 0.3.6, 0.4, 0.5, 0.6, 0.7, 0.7.5, 0.7.6, 0.8, 0.8.1, 0
.8.2, 0.8.3, 0.8.4, 0.8.4.1, 0.8.4.2, 0.8.4.3, 0.8.4.4, 0.8.4.5, 0.8.4.6, 0.8.4.7, 0.8.4.8, 0.8.4.9, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9, 0.9.1, 0.
9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11)
ERROR: No matching distribution found for investpy==0.9.12
```

**Comment by alvarob96** [comment]
Yes you are right I already checked it! I will update the new release to PyPI a few minutes. Sorry for that!

**Comment by alvarob96** [comment]
Hi @kuhytitusdlz! 

**0.9.12 investpy release is now available on PyPI** at https://pypi.org/project/investpy/. So that now you can easily install it via: `python -m pip install investpy==0.9.12`

Thank you for reporting this issue! Make sure to star the repo if you found it useful. :star: :octocat:
