### ISSUE TITLE
Ayuda con Investpy

### ISSUE THREAD

**Issue by D3lt4s** [alvarob96/investpy#90]
Hola Alvaro,

Soy Alexander, finalmente me hice la cuenta en github, te agradezco mucho haber tomado de tu tiempo para responderme por interno, te comento que tengo un incoveniente con el script que me has dejado por interno para que lo pueda usar. 

Cuando ejecuto el script en la terminal....

import investpy

products = ['GBP/USD', 'EUR/USD', 'EUR/JPY']

for product in products:
	result = investpy.get_currency_cross_historical_data(currency_cross=product, from_date='01/01/2018', to_date='01/01/2019')
	result.to_csv(path=product.replace('/', '') + '.csv', index=False)

El sistema imprime en pantalla la siguiente informacion generando un error...

Traceback (most recent call last):
  File "prueba_dos.py", line 7, in <module>
    result.to_csv(path=product.replace('/', '') + '.csv', index=False)
TypeError: to_csv() got an unexpected keyword argument 'path'

He intentado varias cosas pero no lo he conseguido ¿Como puedes solucionar este error?

Por cierto aprovechando esta ocasion para optimizar aun mas el script que instruccion podrias añadir para que por cada paso del bucle exporte un timeframe diario, semanal y mensual de cada instrumento financiero?

Un saludo

**Comment by alvarob96** [comment]
¡Hola @D3lt4s!

Tienes razón, fue un error mío al enviarte el correo, ya que no llegué a lanzar el script por lo que no probé su funcionamiento antes. El error estaba en el parámetro `path` de la llamada a `pandas.DataFrame.to_csv()`, ya que dicho parámetro se llama: `path_or_buf`.

Por tanto, te adjunto el código completo:
```python3
import investpy

products = ['GBP/USD', 'EUR/USD']

for product in products:
    result = investpy.get_currency_cross_historical_data(currency_cross=product, from_date='01/01/2009', to_date='01/01/2019')
    result.to_csv(path_or_buf=product.replace('/', '') + '.csv', index=False)
```

Adicionalmente me comentas sobre la opción de extraer datos en distintas franjas temporales, lo cual es posible utilizando el parámetro `interval` al llamar a las funciones de extracción de datos. De este modo, el código previo por intervalos resultaría de la forma:

```python3
import investpy

products = ['GBP/USD', 'EUR/USD']
intervals = ['Daily', 'Weekly', 'Monthly']

for product in products:
    for interval in intervals:
        result = investpy.get_currency_cross_historical_data(currency_cross=product, from_date='01/01/2009', to_date='01/01/2019', interval=interval)
        result.to_csv(path_or_buf=product.replace('/', '') + '_' + interval + '.csv', index=False)
```

Espero haberte ayudado, cualquier cosa o cuestión no dudes en contactarme (a ser posible en inglés que me es más cómodo y es la forma en que el resto de usuarios puedan enterarse).

¡Un saludo! :star: :octocat:

**Comment by delta-300** [comment]
Hi Alvaro

**Just in case my English isn't clear in some parts, I'll still leave you a section in Spanish.**

Well, At the moment the script is working well and export the retrieved data in CSV format for each request in the array, but I have some issues about that.

I usually use python3.7 to run everything regarding it, when I tried to run your script i got the following reply from the terminal:

Traceback (most recent call last):
File "historicos.py", line 8, in <module>
result = investpy.get_currency_cross_historical_data(currency_cross=product, from_date='01/01/2009', to_date='01/01/2019', interval=interval)
AttributeError: module 'investpy' has no attribute 'get_currency_cross_historical_data'

So again I decided to use the most updated version which is the python3.8 and I tried to run the script so I thought that... it looks like this time this case was solved but when I opened the CSV files with libreoffice calc the data appears in Chinese letters so I tried openning them with Excel, Sublime Text 3 and I finally saw the data for the OHLC (Open,High, Low, Close) but the only drawback is that the dates data column is missing.

why does this happen? and how to fix it?

--

Hola Alvaro,

Bueno, de momento el script funciona bien y exporta los datos recuperados en formato CSV para cada petición del array, pero tengo algunos problemas al respecto aun.

Normalmente uso python3.7 para ejecutar todo lo relacionado con él, cuando intenté ejecutar tu script obtuve la siguiente respuesta de la terminal:

Traceback (most recent call last):
File "historicos.py", line 8, in <module>
result = investpy.get_currency_cross_historical_data(currency_cross=product, from_date='01/01/2009', to_date='01/01/2019', interval=interval)
AttributeError: module 'investpy' has no attribute 'get_currency_cross_historical_data'

Así que de nuevo decidí usar la versión más actualizada que es la python3.8 e intenté ejecutar el script pensando que esta vez el caso estaba resuelto pero cuando abrí los archivos CSV con libreoffice calc los datos aparecen en letras chinas así que intenté abrirlos con Excel, Sublime Text 3 y finalmente vi los datos obtenidos para el OHLC (Open,High, Low, Close) pero el unico incoveniente es que faltan la columna con los datos de las fechas.

¿Por qué ocurre esto? y ¿cómo arreglarlo?

**Comment by alvarob96** [comment]
Hi @delta-300 I will include here a screen capture of the Jupyter Notebook I created so to answer your question so that you can check that it works properly:

![investpy](https://user-images.githubusercontent.com/36760800/71581633-630fcf00-2b06-11ea-8a5d-25c44fed4527.png)

You were not able to see the Date column in the csv file since the index was being removed when using `result.to_csv(path_or_buf='sample.csv', index=False)`, which has been fixed and updated to `result.to_csv(path_or_buf='sample.csv')` since the Date is the `pandas.DataFrame` index.

Anyways, check that you are in the latest investpy release which is the 0.9.12. Also check that you are using Python 3.5 or higher and everything should work as expected. If you still have issues, please notify them to me so that I can fix them or help/answer you if it is a doubt.

**Comment by delta-300** [comment]
Hi Alvaro,

I really wanted to thank you for all support information about these issues. Now everything works out pretty well.

Kind regards
