### ISSUE TITLE
Economic calendar

### ISSUE THREAD

**Issue by misterzyde** [alvarob96/investpy#98]
Hi

Amazing work so far! Would it be possible to add the ability to get the economic calendar (https://www.investing.com/economic-calendar/), ideally with the ability to specify a date range, currency and the importance of the news (which they indicate using bull heads)?

**Comment by alvarob96** [comment]
Hi @misterzyde!

The information you provided above is really useful and I will develop its retrieval right after releasing the 0.9.13 version of investpy (which will be by the end of this week). I also find it useful as you already mentioned and it will not take me too much time to develop.

Thank you for you feedback and support! :star: :octocat:

**Comment by alvarob96** [comment]
ce9674cfe9da6eb6670fb70ced8bcd722cbb8486
